AspNetCoreWithAdminLTE/Models/Proveedores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreWithAdminLTE.Models
{
    public class Proveedores
    {
        [Key]
        public int id { get; set; }


        [Required(ErrorMessage = "El Nombre es Obligatorio")]
        [StringLength(50, ErrorMessage = "El {0} debe tener al menos {2} y maximo {1} caracteres", MinimumLength = 10)]
        [Display(Name = "Nombre")]
        public String Nombre { get; set; }


        [Required(ErrorMessage = "El Email es Obligatorio")]
        [Display(Name = "Email")]
        public String Email { get; set; }

        [Required(ErrorMessage = "El Telefono es Obligatorio")]
        [StringLength(10, ErrorMessage = "El {0} debe tener al menos {2} y maximo {1} caracteres", MinimumLength = 6)]
        [Display(Name = "Telefono")]
        public String Telefono { get; set; }


    }
}

AspNetCoreWithAdminLTE/Controllers/ProveedoresController.cs
using AspNetCoreWithAdminLTE.Data;
using AspNetCoreWithAdminLTE.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreWithAdminLTE.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProveedoresController(ApplicationDbContext context)
        {
            _context = context;
        }
        //TODO: 7. Creamos el Controlador
        public IActionResult Index()
        {
            IEnumerable<Proveedores> listProveedores = _context.Proveedores;
            return View(listProveedores);
        }

        //HTTP GET CREATE
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //HTTP GET CREATE
        [HttpPost]
        public IActionResult Create(Proveedores proveedores)
        {
            if (ModelState.IsValid)
            {
                _context.Proveedores.Add(proveedores);
                _context.SaveChanges();

                TempData["mensaje"] = "El Proveedor Se Ha Guardado Correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var proveedores = _context.Proveedores.Find(id);

            if (proveedores == null)
            {
                return NotFound();
            }

            return View(proveedores);
        }

        [HttpPost]
        public IActionResult Edit(Proveedores proveedores)
        {
            if (ModelState.IsValid)
            {
                _context.Proveedores.Update(proveedores);
                _context.SaveChanges();

                TempData["mensaje"] = "El Proveedor Se Ha Actualizado Correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var proveedores = _context.Proveedores.Find(id);

            if (proveedores == null)
            {
                return NotFound();
            }

            return View(proveedores);
        }


        [HttpPost]
        public IActionResult DeleteProveedores(int? id)
        {

            var proveedores = _context.Proveedores.Find(id);

            if (proveedores == null)
            {
                return NotFound();
            }

            _context.Proveedores.Remove(proveedores);
            _context.SaveChanges();

            TempData["mensaje"] = "El Proveedor Se Ha eliminado Correctamente";
            return RedirectToAction("Index");

        }

    }
}

AspNetCoreWithAdminLTE/Views/Proveedores/Create.cshtml
@model AspNetCoreWithAdminLTE.Models.Proveedores
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .inputs {
        width: 600px;
    }

    .contenedor {
        width: 700px;
        height: 100%;
        background-color: #ffff;
        border-radius: 15px;
    }

    .contenedor2 {
        margin-left: 30px;
    }

    h3 {
        margin-left: 50px;
        margin-top: 40px;
        margin-bottom: 30px;
    }
</style>
<body style="background-color: #eee;">
    <br><br>
        <div class="container contenedor border">
            <div class="row">
                <div class="col-sm-12">
                    <h3>Crear Proveedores</h3>
                </div>
            </div>

            <div class="row">
                <div class="contenedor2 col-sm-10">
                    <form method="post" asp-action="Create">


                        <div class="form-group">
                            <label asp-for="Nombre" class="control-label"></label>
                            <input type="text" asp-for="Nombre" class="form-control" />
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input type="email" asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Telefono" class="control-label"></label>
                            <input type="text" asp-for="Telefono" class="form-control" />
                            <span asp-validation-for="Telefono" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group">
                            <input type="submit" value="Crear Proveedor" class="btn btn-primary" />
                        </div>
                        <br /><br />
                    </form>
                </div>
            </div>
        </div>
</body>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />}
}

AspNetCoreWithAdminLTE/Views/Proveedores/Delete.cshtml
@model AspNetCoreWithAdminLTE.Models.Proveedores
@{
    ViewData["Title"] = "Eliminar Proveedores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .inputs {
        width: 600px;
    }

    .contenedor {
        width: 700px;
        height: 100%;
        background-color: #ffff;
        border-radius: 15px;
    }

    .contenedor2 {
        margin-left: 30px;
    }

    h3 {
        margin-left: 50px;
        margin-top: 40px;
        margin-bottom: 30px;
    }
</style>

<div class="contenedor container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar Proveedor</h3>
        </div>
    </div>

    <div class="row">
        <div class="contenedor2 col-sm-10">
            <form method="post" asp-action="DeleteProveedores">

                <input type="hidden" asp-for="id" />

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input type="text" asp-for="Nombre" class="form-control" disabled />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input type="email" asp-for="Email" class="form-control" disabled />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Telefono" class="control-label"></label>
                    <input type="text" asp-for="Telefono" class="form-control" disabled />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <br />
                <div class="inputs form-group">
                    <input type="submit" value="Eliminar Proveedor" class="btn btn-primary" />
                </div>
                <br /><br />
            </form>
        </div>
    </div>
</div>

@section Scripts{

    @{<partial name="_ValidationScriptsPartial" />}
}

AspNetCoreWithAdminLTE/Views/Proveedores/Edit.cshtml
@model AspNetCoreWithAdminLTE.Models.Proveedores
@{
    ViewData["Title"] = "Editar Proveedores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .inputs {
        width: 600px;
    }

    .contenedor {
        width: 700px;
        height: 100%;
        background-color: #ffff;
        border-radius: 15px;
    }

    .contenedor2 {
        margin-left: 30px;
    }

    h3 {
        margin-left: 50px;
        margin-top: 40px;
        margin-bottom: 30px;
    }
</style>
<body style="background-color: #eee;">
    <br><br>
    <div class="container contenedor border">
        <div class="row">
            <div class="col-sm-12">
                <h3>Editar Empleado</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-10 contenedor2">
                <form method="post" asp-action="Edit">

                    <input type="hidden" asp-for="id" />

                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input type="text" asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input type="email" asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input type="text" asp-for="Telefono" class="form-control" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <br />
                    <div class="form-group">
                        <input type="submit" value="Editar Proveedor" class="btn btn-primary" />
                    </div>
                    <br /><br />
                </form>
            </div>
        </div>
    </div>
</body>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />}
}

AspNetCoreWithAdminLTE/Views/Proveedores/Index.cshtml
@model IEnumerable<AspNetCoreWithAdminLTE.Models.Proveedores>
    <style>

        .BotonR {
            width: 200px;
            color: white;
            background-color: #1ea0e8;
            margin-left: 10px;
        }

            .BotonR:hover {
                background-color: #246E97;
                color: white;
            }

        .encabezado {
            color: #246E97;
        }
    </style>
    @{
        ViewData["Title"] = "Lista De Proveedores";
        Layout = "~/Views/Shared/_Layout.cshtml";
        //TODO: 8. Creamos La vista
    }

<div class="container">

    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3>Lista De Proveedores</h3>
        </div>
    </div>

    <div style="margin-left: 800px" class="row">
        <div class="col-sm-6">
            <a asp-controller="Proveedores" asp-action="Create" class="BotonR btn d-block">Agregar Proveedores</a>
        </div>
    </div>


    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped" id="tabla">
                <thead>
                    <tr class="encabezado">
                        <td>@Html.DisplayNameFor(m => m.id)</td>
                        <td>@Html.DisplayNameFor(m => m.Nombre)</td>
                        <td>@Html.DisplayNameFor(m => m.Email)</td>
                        <td>@Html.DisplayNameFor(m => m.Telefono)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.id</td>
                            <td>@item.Nombre</td>
                            <td>@item.Email</td>
                            <td>@item.Telefono</td>
                            <td>
                                <a asp-controller="Proveedores" asp-action="Edit" asp-route-id="@item.id" ><i class="fas fa-edit"></i></a>
                                <a asp-controller="Proveedores" asp-action="Delete" asp-route-id="@item.id"><i class="fas fa-user-times"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No Hay Registros De Proveedores </p>
        }
    </div>
</div>
    @section Scripts{
        <script src="~/js/tabla.js"></script>
    }